#!/usr/bin/env python3
"""Generate INDEX.md and docs/families/*.md from registry.json.

    python3 generate_docs.py            # write
    python3 generate_docs.py --check    # exit 1 if anything is out of date (CI)

The markdown exists so the catalogue stays greppable and human-browsable - grep over reference
files is an officially recommended navigation pattern, and route.py cannot be the only way in. But
two sources of truth drift, so these files are generated and never hand-edited, and CI fails on any
difference.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REGISTRY = ROOT / "registry.json"
INDEX = ROOT / "INDEX.md"
FAMILY_DIR = ROOT / "docs" / "families"

BANNER = "<!-- GENERATED by generate_docs.py from registry.json. Do not edit by hand. -->"

LIMB = {
    "a": "encodes a fact the agent has no way to know it doesn't know",
    "b": "corrects a formula that is reliably got wrong",
    "c": "refuses something that would otherwise be done confidently",
}


def render_index(reg: dict) -> str:
    lines = [BANNER, "", "# Statistical judgment — index", "",
             "Find a model by running the router; it costs no context until called:", "",
             "```", 'python3 route.py "your predicament, in plain words"', "```", "",
             "Or browse by the question you are asking.", "",
             "| Family | The question | Models |", "|---|---|---|"]
    for fam in reg["families"]:
        members = [m for m in reg["models"] if m["family"] == fam["id"]]
        lines.append(f"| [{fam['id']}](docs/families/{fam['id']}.md) | {fam['question']} | "
                     f"{len(members)} |")
    lines += ["", f"**{len(reg['models'])} models across {len(reg['families'])} families.**", "",
              "Every model earns its place by doing something a capable agent working unaided "
              "demonstrably could not — see `evals/baselines/RESULTS.md` for the measurements "
              "that set that bar. Computation alone does not qualify.", ""]
    return "\n".join(lines)


def render_family(fam: dict, members: list) -> str:
    lines = [BANNER, "", f"# {fam['id']} — {fam['question']}", "", "## Contents", ""]
    for m in members:
        lines.append(f"- [{m['title']}](#{m['id']}) — {m['output']}")
    lines.append("")
    for m in members:
        lines += [f"## {m['title']}", "", f'<a id="{m["id"]}"></a>', "",
                  f"**When:** {m['situations'][0]}  ",
                  f"**Tier:** `{m['tier']}`  ",
                  f"**Earns its place by:** {LIMB[m['selection_limb']]}", "",
                  "```", f"python3 {m['path']} {m['usage']}", "```", "",
                  f"**Returns:** {m['output']}", ""]
        if m.get("baseline_to_beat"):
            lines += [f"**Must beat:** {m['baseline_to_beat']} — if it does not, the script prints "
                      f"that answer instead and exits 5.", ""]
        lines += ["**Also asked as:**", ""]
        lines += [f"- {s}" for s in m["situations"][1:]]
        lines.append("")
        if m.get("refuses_when"):
            lines += [f"**Refuses (exit 3) when:** {m['refuses_when']}", ""]
        if m.get("unanswerable_when"):
            lines += [f"**Unanswerable (exit 4) when:** {m['unanswerable_when']}", ""]
        for h in m.get("composition_hazards") or []:
            lines += [f"**Hazard:** {h}", ""]
        if m.get("data_provenance_required"):
            lines += [f"**Requires of the data:** {m['data_provenance_required']}", ""]
        if m.get("independence_required"):
            lines += ["**Requires independence:** observations must not share a generator. "
                      "Repeated runs of one process, or several agents querying one model, are "
                      "not independent observations.", ""]
        lines += [f"*Why it exists:* {m['evidence']}", "", "---", ""]
    return "\n".join(lines)


def build(reg: dict) -> dict:
    out = {INDEX: render_index(reg)}
    for fam in reg["families"]:
        members = [m for m in reg["models"] if m["family"] == fam["id"]]
        out[FAMILY_DIR / f"{fam['id']}.md"] = render_family(fam, members)
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate docs from registry.json.")
    ap.add_argument("--check", action="store_true", help="exit 1 if any file is out of date")
    a = ap.parse_args(argv)

    reg = json.loads(REGISTRY.read_text())
    wanted = build(reg)

    if a.check:
        stale = [p for p, text in wanted.items()
                 if not p.exists() or p.read_text() != text]
        # A family file left behind after its family is removed is also drift.
        known = set(wanted)
        orphans = [p for p in FAMILY_DIR.glob("*.md") if p not in known] \
            if FAMILY_DIR.exists() else []
        if stale or orphans:
            for p in stale:
                print(f"out of date: {p.relative_to(ROOT)}", file=sys.stderr)
            for p in orphans:
                print(f"orphaned: {p.relative_to(ROOT)}", file=sys.stderr)
            print("\nRun: python3 generate_docs.py", file=sys.stderr)
            return 1
        print(f"docs up to date ({len(wanted)} files)")
        return 0

    FAMILY_DIR.mkdir(parents=True, exist_ok=True)
    for p, text in wanted.items():
        p.write_text(text)
    for p in FAMILY_DIR.glob("*.md"):
        if p not in wanted:
            p.unlink()
            print(f"removed orphan {p.relative_to(ROOT)}")
    print(f"wrote {len(wanted)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
